### ISSUE TITLE
Cannot use ::class with dynamic class name

### ISSUE THREAD

**Issue by SamLNL** [nystudio107/craft-twigfield#4]
### Description
I just updated my website which is running on php 7.4. With this update, craft-twigfield was updated from 1.0.11 to 1.0.14.
This causes a intern server error whenever I tried to access the cms:

![Screenshot at Oct 14 12-10-39](https://user-images.githubusercontent.com/21331474/195822180-91cf33c9-f862-4644-87e0-316d80271306.png)

The logs are showing:

`PHP Fatal error:  Cannot use ::class with dynamic class name in /projects/veluwseon_88/vendor/nystudio107/craft-twigfield/src/services/AutocompleteService.php on line 138`

### Fix
Updating to php 8.1.4 fixed it for me. I just thought I'd mention it..

### Versions
- Plugin version: 1.0.14
- Craft version: 3.7.56

**Comment by garycrane** [comment]
Same here: 

`PHP Fatal error:  Dynamic class names are not allowed in compile-time ::class fetch in /home/vendor/nystudio107/craft-twigfield/src/services/AutocompleteService.php on line 138`

PHP7.4

**Comment by ohlincik** [comment]
Same here on PHP7.4 and PHP7.2 (looks like this may be only happening with `phpfpm`)

**Comment by mofman** [comment]
Took a few of our sites offline too

**Comment by ohlincik** [comment]
The actual site still worked fine for us. It was just not possible to access the CMS Control Panel at all. Had to revert the update for the time being. On our setup, the issue manifested itself as a `502 Bad Gateway` error from NGINX.

**Comment by Saboteur777** [comment]
Just ran into this, too, with PHP 7.4.

**Comment by ephb** [comment]
It just happened to me too. Thank you @SamLNL for mentioning a fix.

**Comment by torgeirbeyer** [comment]
Is there a fix for this without the need to update to php 8.1.4? We are experiencing the same issue on one of our sites, and we're not ready to update yet.

**Comment by Saboteur777** [comment]
@torgeirbeyer  A temporary fix could be to add `"nystudio107/craft-twigfield": "1.0.11"` to your composer.json and run a `composer update`.

**Comment by torgeirbeyer** [comment]
@Saboteur777 Thanks! Just fixed it.

**Comment by Saboteur777** [comment]
You are welcome. Once the patch is out, you can remove this line and everything will be back to normal.

**Comment by seb-jones** [comment]
We are also hitting this error.

**Comment by khalwat** [comment]
Sorry for this one...

Addressed in: https://github.com/nystudio107/craft-twigfield/commit/bff508e2e239fd55b8a17ea56fc60db5e655f418

Released as Twigfield 1.0.15: https://github.com/nystudio107/craft-twigfield/releases/tag/1.0.15

You can update to it by doing:

```
composer update nystudio107/craft-twigfield
```

**Comment by khalwat** [comment]
Anyone who had this issue, and updated to the latest Twigfield, if you could affirm that it has fixed the issue for you, I'd appreciate you posting that here.

**Comment by Saboteur777** [comment]
@khalwat It seems the issue has been fixed, thank you!

**Comment by garycrane** [comment]
@khalwat Yes, working for me too. Many thanks.
